---
- hosts: pi1
  gather_facts: yes
  become: yes
  tasks:
      # apt-get update
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

      # apt-get upgrade
    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes
